"""
email_followup.py
-----------------
Generates professional vendor follow-up emails for overdue invoices.
Uses GPT-4o when API key is available; falls back to polished templates.
"""

import datetime

# ── Template fallbacks ─────────────────────────────────────────────────────────

TEMPLATES = {
    "gentle": {
        "subject": "Friendly Reminder: Invoice {invoice_id} — Payment Due",
        "body": """Dear {vendor_name} Finance Team,

I hope this message finds you well.

I'm reaching out regarding invoice {invoice_id} for {description}, 
totalling {currency} {amount:,.2f}, which was due on {due_date}.

Could you please confirm the expected payment date at your earliest convenience? 
If the payment has already been processed, kindly disregard this message and share 
the remittance details so we can update our records.

Thank you for your continued partnership.

Best regards,  
Finance Operations Team  
Workfully S.L."""
    },

    "firm": {
        "subject": "ACTION REQUIRED: Overdue Invoice {invoice_id} — {days_overdue} Days Past Due",
        "body": """Dear {vendor_name} Finance Team,

This is a formal follow-up regarding invoice {invoice_id} for {description}, 
totalling {currency} {amount:,.2f}.

This invoice was due on {due_date} and is now {days_overdue} days overdue.

We kindly request immediate payment or a confirmed payment date by return email. 
If there are any discrepancies or concerns regarding this invoice, please contact 
us directly so we can resolve them promptly.

Please note that continued non-payment may affect our business relationship.

Regards,  
Finance Operations Team  
Workfully S.L."""
    },

    "escalation": {
        "subject": "URGENT: Invoice {invoice_id} — Escalation Notice ({days_overdue} Days Overdue)",
        "body": """Dear {vendor_name},

Despite previous communications, invoice {invoice_id} for {currency} {amount:,.2f} 
remains unpaid as of today. This invoice was due on {due_date} and is now 
{days_overdue} days past due.

This matter has been escalated internally and requires immediate resolution.

Please arrange payment within 5 business days or contact our Finance Director 
directly to discuss a payment arrangement. Failure to do so may result in 
suspension of services and/or formal collections proceedings.

This is an automated notice generated by the Workfully Finance Ops system.

Finance Operations — Workfully S.L."""
    }
}


def _choose_template(days_overdue: int) -> str:
    if days_overdue < 15:
        return "gentle"
    elif days_overdue < 45:
        return "firm"
    else:
        return "escalation"


def _format_template(template_key: str, context: dict) -> dict:
    t = TEMPLATES[template_key]
    return {
        "subject": t["subject"].format(**context),
        "body":    t["body"].format(**context),
        "tone":    template_key.capitalize(),
        "method":  "template",
    }


def _gpt4o_email(context: dict, openai_client) -> dict:
    """Generate a personalised follow-up email using GPT-4o."""
    days = context["days_overdue"]
    tone = "polite but urgent" if days > 30 else "friendly and professional"

    prompt = f"""You are a finance operations assistant at Workfully, a Barcelona-based startup.
Write a {tone} vendor payment follow-up email for the details below.

Invoice ID:   {context['invoice_id']}
Vendor:       {context['vendor_name']}
Description:  {context['description']}
Amount:       {context['currency']} {context['amount']:,.2f}
Due Date:     {context['due_date']}
Days Overdue: {context['days_overdue']}

Return ONLY a JSON object with keys: "subject", "body"
- Keep body under 200 words
- Be professional but human
- Do not use markdown in the body
- Sign off as "Finance Operations Team, Workfully S.L."
"""

    response = openai_client.chat.completions.create(
        model="gpt-4o",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.4,
        max_tokens=400,
        response_format={"type": "json_object"},
    )

    import json
    data = json.loads(response.choices[0].message.content)
    data["tone"] = "AI-generated"
    data["method"] = "gpt-4o"
    return data


# ── Public API ─────────────────────────────────────────────────────────────────

def generate_followup_email(
    invoice_id: str,
    vendor_name: str,
    description: str,
    amount: float,
    currency: str,
    due_date: str,
    days_overdue: int,
    openai_client=None,
) -> dict:
    """
    Generate a follow-up email for an overdue invoice.
    Returns: {subject, body, tone, method}
    """
    context = {
        "invoice_id":   invoice_id,
        "vendor_name":  vendor_name,
        "description":  description,
        "amount":       amount,
        "currency":     currency,
        "due_date":     due_date,
        "days_overdue": days_overdue,
        "today":        datetime.date.today().strftime("%B %d, %Y"),
    }

    if openai_client is not None:
        try:
            return _gpt4o_email(context, openai_client)
        except Exception as e:
            print(f"GPT-4o email generation failed ({e}), using template")

    template_key = _choose_template(days_overdue)
    return _format_template(template_key, context)


def get_all_followups(df, openai_client=None) -> list[dict]:
    """
    Generate follow-up emails for all overdue invoices in a DataFrame.
    Returns list of email dicts with invoice metadata attached.
    """
    overdue = df[df["status"] == "Overdue"].copy()
    results = []
    for _, row in overdue.iterrows():
        email = generate_followup_email(
            invoice_id=row["invoice_id"],
            vendor_name=row["vendor_name"],
            description=row["description"],
            amount=float(row["amount"]),
            currency=row.get("currency", "EUR"),
            due_date=str(row["due_date"]),
            days_overdue=int(row.get("days_overdue", 0)),
            openai_client=openai_client,
        )
        email["invoice_id"]   = row["invoice_id"]
        email["vendor_name"]  = row["vendor_name"]
        email["vendor_email"] = row.get("vendor_email", "")
        email["amount"]       = float(row["amount"])
        email["days_overdue"] = int(row.get("days_overdue", 0))
        results.append(email)

    # Sort: most overdue first
    results.sort(key=lambda x: x["days_overdue"], reverse=True)
    return results
