"""
invoice_extractor.py
--------------------
Extracts structured data from uploaded PDF invoices using GPT-4o vision.
Falls back to pdfplumber text extraction + heuristic parsing if no API key.
"""

import os
import re
import json
import base64
import datetime
import pdfplumber


# ── Helpers ────────────────────────────────────────────────────────────────────

def _pdf_to_text(pdf_path: str) -> str:
    """Extract raw text from a PDF file."""
    text = ""
    with pdfplumber.open(pdf_path) as pdf:
        for page in pdf.pages:
            text += (page.extract_text() or "") + "\n"
    return text.strip()


def _pdf_to_base64(pdf_path: str) -> str:
    with open(pdf_path, "rb") as f:
        return base64.b64encode(f.read()).decode("utf-8")


def _heuristic_parse(text: str) -> dict:
    """
    Lightweight regex-based parser used when no OpenAI API key is present.
    Handles the PDF format generated by generate_sample_data.py.
    """
    def find(patterns, default="N/A"):
        for p in patterns:
            m = re.search(p, text, re.IGNORECASE)
            if m:
                return m.group(1).strip()
        return default

    amount_raw = find([
        r"TOTAL\s+€\s*([\d,]+\.?\d*)",
        r"Amount.*?€\s*([\d,]+\.?\d*)",
        r"€\s*([\d,]+\.\d{2})",
    ])
    try:
        amount = float(amount_raw.replace(",", ""))
    except ValueError:
        amount = 0.0

    return {
        "invoice_id":   find([r"(INV-\d{4}-\d{4})", r"Invoice\s*#?\s*(\S+)"]),
        "vendor_name":  find([r"FROM\s*\n([^\n]+)", r"Vendor[:\s]+([^\n]+)"]),
        "vendor_email": find([r"([\w.\-]+@[\w.\-]+\.\w+)"]),
        "description":  find([r"Description\s*Category.*?\n([^\n]+)"]),
        "category":     find([r"Category\s+Amount.*?\n[^\n]+\s+([A-Za-z ]+)\s+€"]),
        "amount":       amount,
        "currency":     "EUR",
        "issue_date":   find([r"(\d{4}-\d{2}-\d{2})"]),
        "due_date":     find([r"Due Date\s*\n(\d{4}-\d{2}-\d{2})"]),
        "status":       find([r"Status\s*\n(\w+)", r"(Paid|Overdue|Pending|Disputed)"]),
        "notes":        "",
        "extraction_method": "heuristic",
    }


def _gpt4o_parse(pdf_path: str, client) -> dict:
    """Use GPT-4o to extract structured invoice data."""
    text = _pdf_to_text(pdf_path)

    prompt = f"""You are a precise finance data extraction assistant.
Extract ALL of the following fields from the invoice text below.
Return ONLY valid JSON with these exact keys:

{{
  "invoice_id":   "...",
  "vendor_name":  "...",
  "vendor_email": "...",
  "description":  "...",
  "category":     "...",
  "amount":       0.00,
  "currency":     "EUR",
  "issue_date":   "YYYY-MM-DD",
  "due_date":     "YYYY-MM-DD",
  "status":       "Paid|Overdue|Pending|Disputed",
  "notes":        "..."
}}

Rules:
- amount must be a float (no currency symbols)
- dates must be YYYY-MM-DD format
- If a field is missing, use null
- status must be exactly one of: Paid, Overdue, Pending, Disputed

INVOICE TEXT:
{text}
"""

    response = client.chat.completions.create(
        model="gpt-4o",
        messages=[{"role": "user", "content": prompt}],
        temperature=0,
        max_tokens=500,
        response_format={"type": "json_object"},
    )

    raw = response.choices[0].message.content
    data = json.loads(raw)
    data["extraction_method"] = "gpt-4o"
    return data


# ── Public API ─────────────────────────────────────────────────────────────────

def extract_invoice(pdf_path: str, openai_client=None) -> dict:
    """
    Main entry point. Returns a dict of extracted invoice fields.
    Uses GPT-4o if client is provided, otherwise falls back to heuristics.
    """
    if openai_client is not None:
        try:
            return _gpt4o_parse(pdf_path, openai_client)
        except Exception as e:
            print(f"GPT-4o extraction failed ({e}), falling back to heuristics")

    text = _pdf_to_text(pdf_path)
    return _heuristic_parse(text)


def compute_status(due_date_str: str, paid_date_str: str) -> dict:
    """
    Compute live payment status and days overdue from dates.
    Returns: {status, days_overdue, urgency_label, urgency_color}
    """
    today = datetime.date.today()

    try:
        due = datetime.date.fromisoformat(due_date_str)
    except Exception:
        return {"status": "Unknown", "days_overdue": 0,
                "urgency_label": "⚪ Unknown", "urgency_color": "#6b7280"}

    if paid_date_str:
        return {"status": "Paid", "days_overdue": 0,
                "urgency_label": "✅ Paid", "urgency_color": "#16a34a"}

    days_overdue = (today - due).days

    if days_overdue > 0:
        if days_overdue > 60:
            label, color = f"🔴 Overdue {days_overdue}d", "#dc2626"
        elif days_overdue > 30:
            label, color = f"🟠 Overdue {days_overdue}d", "#ea580c"
        else:
            label, color = f"🟡 Overdue {days_overdue}d", "#d97706"
        return {"status": "Overdue", "days_overdue": days_overdue,
                "urgency_label": label, "urgency_color": color}

    days_until = -days_overdue
    if days_until <= 7:
        label, color = f"⚠️ Due in {days_until}d", "#f59e0b"
    else:
        label, color = f"🟢 Due in {days_until}d", "#2563eb"
    return {"status": "Pending", "days_overdue": 0,
            "urgency_label": label, "urgency_color": color}
